# Development Environment Configuration
# Used for local development with Docker containers

spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/bookreview
    username: bookreview_user
    password: bookreview_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Configuration - enabled for database migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
    default-schema: public
  
  # Security Configuration - disabled temporarily
  security:
    user:
      name: admin
      password: admin123
  
  # Redis Configuration for Development
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Mail Configuration for Development (Console Output)
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  
  # DevTools Configuration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Logging Configuration for Development
logging:
  level:
    com.bookreview: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/bookreview-dev.log

# Development-specific Application Configuration
app:
  jwt:
    secret: dev-jwt-secret-key-not-secure
  
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
      - http://127.0.0.1:3000
  
  aws:
    s3:
      bucket: bookreview-images-dev
  
  # Relaxed rate limiting for development
  rate-limit:
    enabled: false
